# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20170215_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCustomerUserPercentageBenefit',
            fields=[
                ('benefit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.Benefit')),
                ('enterprise_customer_uuid', models.UUIDField(help_text='UUID for an EnterpriseCustomer from the Enterprise Service.')),
            ],
            options={
                'verbose_name': 'Percentage enterprise entitlement discount benefit',
                'verbose_name_plural': 'Percentage enterprise entitlement discount benefits',
            },
            bases=('offer.benefit',),
        ),
    ]
